#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 10 14:34:55 2022

@author: njk
"""

import os

# ----------------------- Parameters & Variables -----------------------------

# Path to location of geojsons used to define geographical extents.
dir_path ='./ctrl_pgon'

Year = 2022

# Loops over all geojsons in the ctrl_pgon folder.
fnames =([file for root, dirs, files in os.walk(dir_path)
          for file in files
              if file.endswith('.json')])
for fname in fnames: os.system("./request_and_process_data.py {} {}".format(fname, Year))
